import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JavaScript Games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/Juanmarin444/JavaScript-Games" target='_blank' rel="noreferrer">JavaScript Games!</a>
        </h1>

        <p className={styles.description}>
          Choose a game to play
        </p>

        <div className={styles.grid}>
          <Link href="/memory-game">
            <a  className={styles.card}>
              <h2>Memory Game &rarr;</h2>
              <p>Find the matching pairs.</p>
            </a>
          </Link>

          <Link href="/space-invader">
            <a  className={styles.card}>
              <h2>Space Invaders &rarr;</h2>
              <p>Protect Earth from an alien invasion.</p>
            </a>
          </Link>

          <Link href="/whac-a-mole">
            <a  className={styles.card}>
              <h2>Whac-A-Mole &rarr;</h2>
              <p>Keep your gardens safe from the mole invasion!</p>
            </a>
          </Link>

          <Link href="/connect-four">
            <a className={styles.card}>
              <h2>Connect-Four &rarr;</h2>
              <p>Challenge a friend to a game of connect-four!</p>
            </a>
          </Link>

          <Link href="/snake">
            <a className={styles.card}>
              <h2>Snake &rarr;</h2>
              <p>{`Play snake if you're bored!`}</p>
            </a>
          </Link>

          <Link href="/">
            <a className={styles.card}>
              <h2>Some Other Game &rarr;</h2>
              <p>Some other game.</p>
            </a>
          </Link>
        </div>
      </main>
      <Footer />
    </div>
  )
}
