import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Footer from '../components/memory-game/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JavaScript Games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">JavaScript Games!</a>
        </h1>

        <p className={styles.description}>
          Choose a game to play
        </p>

        <div className={styles.grid}>
          <Link href="/memory-game">
            <a  className={styles.card}>
              <h2>Memory Game &rarr;</h2>
              <p>Find the matching pairs.</p>
            </a>
          </Link>

          <Link href="/space-invader">
            <a  className={styles.card}>
              <h2>Space Invaders &rarr;</h2>
              <p>Protect Earth from an alien invasion.</p>
            </a>
          </Link>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Some Other Game &rarr;</h2>
            <p>Some other game.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>A Different Game &rarr;</h2>
            <p>
              A different game.
            </p>
          </a>
        </div>
      </main>
      
      <Footer />
    </div>
  )
}
